import type { Application, Interview, Reminder, TimelineEvent } from "@/types/application";

export const applications: Application[] = [
  {
    id: "tencent-pm",
    userId: "demo-user",
    companyName: "腾讯",
    position: "产品经理",
    category: "产品",
    city: "深圳",
    source: "内推",
    status: "一面",
    track: "campus",
    applyDate: "2026-08-20",
    jobUrl: "https://careers.tencent.com",
    description: "负责内容产品的用户增长、需求分析、数据跟踪和跨团队推进。",
    notes: "重点准备产品sense、校园项目复盘和常见增长指标。",
    createdAt: "2026-08-20T09:00:00Z",
    updatedAt: "2026-08-26T10:00:00Z",
  },
  {
    id: "bytedance-ops",
    userId: "demo-user",
    companyName: "字节跳动",
    position: "用户运营",
    category: "运营",
    city: "北京",
    source: "BOSS直聘",
    status: "笔试",
    track: "campus",
    applyDate: "2026-08-18",
    jobUrl: "https://jobs.bytedance.com",
    description: "围绕用户生命周期设计运营策略，提升留存与活跃。",
    notes: "笔试前复习数据分析、活动策划和用户分层案例。",
    createdAt: "2026-08-18T09:00:00Z",
    updatedAt: "2026-08-24T12:00:00Z",
  },
  {
    id: "alibaba-tech",
    userId: "demo-user",
    companyName: "阿里巴巴",
    position: "前端开发工程师",
    category: "技术",
    city: "杭州",
    source: "公司官网",
    status: "已投递",
    track: "campus",
    applyDate: "2026-08-16",
    jobUrl: "https://talent.alibaba.com",
    description: "参与电商业务前端研发，关注性能、稳定性和工程效率。",
    notes: "准备 JavaScript 基础、React、项目难点和算法题。",
    createdAt: "2026-08-16T09:00:00Z",
    updatedAt: "2026-08-16T09:00:00Z",
  },
  {
    id: "meituan-finance",
    userId: "demo-user",
    companyName: "美团",
    position: "财务分析管培生",
    category: "财务",
    city: "上海",
    source: "学校就业网",
    status: "二面",
    track: "campus",
    applyDate: "2026-08-12",
    jobUrl: "https://zhaopin.meituan.com",
    description: "参与经营分析、预算管理和业务财务支持。",
    notes: "二面偏业务理解，复盘上一轮对本地生活业务的回答。",
    createdAt: "2026-08-12T09:00:00Z",
    updatedAt: "2026-08-27T09:00:00Z",
  },
  {
    id: "netease-marketing",
    userId: "demo-user",
    companyName: "网易",
    position: "品牌市场专员",
    category: "市场",
    city: "广州",
    source: "猎聘",
    status: "准备投递",
    track: "campus",
    applyDate: "2026-08-28",
    jobUrl: "https://hr.163.com",
    description: "参与品牌传播、用户洞察、内容策划和市场活动落地。",
    notes: "简历还需要突出社团活动和内容策划案例。",
    createdAt: "2026-08-25T09:00:00Z",
    updatedAt: "2026-08-25T09:00:00Z",
  },
  {
    id: "xiaomi-mt",
    userId: "demo-user",
    companyName: "小米",
    position: "管培生",
    category: "管培",
    city: "北京",
    source: "公司官网",
    status: "Offer",
    track: "campus",
    applyDate: "2026-08-05",
    jobUrl: "https://hr.xiaomi.com",
    description: "轮岗培养，参与消费电子业务、零售渠道与供应链协同。",
    notes: "已收到口头 Offer，等待正式邮件。",
    createdAt: "2026-08-05T09:00:00Z",
    updatedAt: "2026-08-29T09:00:00Z",
  },
  {
    id: "baidu-product",
    userId: "demo-user",
    companyName: "百度",
    position: "AI产品助理",
    category: "产品",
    city: "北京",
    source: "内推",
    status: "拒绝",
    track: "campus",
    applyDate: "2026-08-01",
    jobUrl: "https://talent.baidu.com",
    description: "协助 AI 搜索产品需求分析和竞品研究。",
    notes: "一面后未通过，复盘时发现 AI 产品商业化回答偏浅。",
    createdAt: "2026-08-01T09:00:00Z",
    updatedAt: "2026-08-21T09:00:00Z",
  },
];

export const timelineEvents: TimelineEvent[] = [
  {
    id: "event-1",
    userId: "demo-user",
    applicationId: "tencent-pm",
    eventType: "投递",
    eventDate: "2026-08-20",
    title: "完成投递",
    track: "campus",
    description: "通过内推链接提交产品经理岗位。",
    createdAt: "2026-08-20T09:00:00Z",
  },
  {
    id: "event-2",
    userId: "demo-user",
    applicationId: "bytedance-ops",
    eventType: "笔试",
    eventDate: "2026-08-25",
    title: "收到笔试通知",
    track: "campus",
    description: "笔试时间为 19:00，题型包含数据分析和运营案例。",
    createdAt: "2026-08-24T10:00:00Z",
  },
  {
    id: "event-3",
    userId: "demo-user",
    applicationId: "tencent-pm",
    eventType: "面试",
    eventDate: "2026-09-01",
    title: "完成一面",
    track: "campus",
    description: "重点问了校园项目、需求优先级和数据指标。",
    createdAt: "2026-09-01T10:00:00Z",
  },
  {
    id: "event-4",
    userId: "demo-user",
    applicationId: "meituan-finance",
    eventType: "面试",
    eventDate: "2026-09-03",
    title: "二面预约成功",
    track: "campus",
    description: "面试官来自业务财务团队，需准备经营分析案例。",
    createdAt: "2026-08-27T09:00:00Z",
  },
  {
    id: "event-5",
    userId: "demo-user",
    applicationId: "xiaomi-mt",
    eventType: "Offer",
    eventDate: "2026-09-05",
    title: "收到口头 Offer",
    track: "campus",
    description: "HR 确认岗位意向，预计一周内发正式邮件。",
    createdAt: "2026-09-05T09:00:00Z",
  },
];

export const interviews: Interview[] = [
  {
    id: "interview-1",
    userId: "demo-user",
    applicationId: "tencent-pm",
    round: "第一次面试",
    interviewDate: "2026-09-01T10:00:00+08:00",
    questions: "如何判断一个校园社区功能是否值得做？如果数据下滑你会怎么排查？",
    answers: "先明确目标用户和核心场景，再看留存、使用频次和转化路径。数据下滑分渠道、版本、用户群和漏斗步骤排查。",
    notes: "回答结构还可以，但案例细节不够具体，需要补充数据口径。",
    result: "等待结果",
    createdAt: "2026-09-01T12:00:00Z",
    updatedAt: "2026-09-01T12:00:00Z",
  },
  {
    id: "interview-2",
    userId: "demo-user",
    applicationId: "meituan-finance",
    round: "第二次面试",
    interviewDate: "2026-09-03T15:00:00+08:00",
    questions: "如何理解本地生活平台的经营效率？",
    answers: "从供给密度、履约成本、补贴效率和用户复购几个维度拆解。",
    notes: "需要准备一页业务框架，避免只讲概念。",
    result: "已预约",
    createdAt: "2026-08-27T10:00:00Z",
    updatedAt: "2026-08-27T10:00:00Z",
  },
];

export const reminders: Reminder[] = [
  {
    id: "reminder-1",
    userId: "demo-user",
    applicationId: "bytedance-ops",
    title: "字节跳动用户运营笔试",
    remindAt: "2026-08-25T19:00:00+08:00",
    type: "笔试",
    track: "campus",
    isDone: false,
    createdAt: "2026-08-24T10:00:00Z",
  },
  {
    id: "reminder-2",
    userId: "demo-user",
    applicationId: "tencent-pm",
    title: "腾讯产品经理一面复盘",
    remindAt: "2026-09-01T21:00:00+08:00",
    type: "复盘",
    track: "campus",
    isDone: false,
    createdAt: "2026-08-26T10:00:00Z",
  },
  {
    id: "reminder-3",
    userId: "demo-user",
    applicationId: "meituan-finance",
    title: "美团财务分析二面",
    remindAt: "2026-09-03T15:00:00+08:00",
    type: "面试",
    track: "campus",
    isDone: false,
    createdAt: "2026-08-27T09:00:00Z",
  },
];